#define WRIST_ENABLE_PIN 22
#define WRIST_DIR_PIN 24
#define WRIST_STEP_PIN 26

#define FOREARM_ENABLE_PIN 30
#define FOREARM_DIR_PIN 32
#define FOREARM_STEP_PIN 34

#define ELBOW_ENABLE_PIN 38
#define ELBOW_DIR_PIN 40
#define ELBOW_STEP_PIN 42

#define SHOULDER_ENABLE_PIN 46
#define SHOULDER_DIR_PIN 48
#define SHOULDER_STEP_PIN 50

#define REVERSE_SHOULDER_ENABLE_PIN 49
#define REVERSE_SHOULDER_DIR_PIN 51
#define REVERSE_SHOULDER_STEP_PIN 53
