// CLK == step
// CW == DIR
// EN == EN


#define WRIST_STEP_PIN 53
#define WRIST_DIR_PIN 51
#define WRIST_ENABLE_PIN 49

#define FOREARM_STEP_PIN 47
#define FOREARM_DIR_PIN 45
#define FOREARM_ENABLE_PIN 43

#define ELBOW_STEP_PIN 41
#define ELBOW_DIR_PIN 39
#define ELBOW_ENABLE_PIN 37

#define SHOULDER_STEP_PIN 35
#define SHOULDER_DIR_PIN 33
#define SHOULDER_ENABLE_PIN 31

#define REVERSE_SHOULDER_STEP_PIN 29
#define REVERSE_SHOULDER_DIR_PIN 21
#define REVERSE_SHOULDER_ENABLE_PIN 25

#define BASE_STEP_PIN 28
#define BASE_DIR_PIN 26
#define BASE_ENABLE_PIN 24

#define POT_PIN 1